### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by coolaj86** [dashhive/DashPlatform.js#1]
- [x] Create DIP9/DIP13 key for identity
- [ ] Create the other 4 keys for an idenity
- [ ] Broadcast via Tx
- [ ] Broadcast via GRPC

Resources

- https://github.com/dashpay/dips/blob/master/dip-0013.md

**Comment by coolaj86** [comment]
We may be able to sidestep all of the WASM, etc. The process may be this simple:

1. Create a wallet with a few BIP44 and DIP9 HD accounts
2. Generate private and public keys
3. Send an `assetLock` payment, which is an almost normal transaction, but with a burn memo for the same amount as some special outputs appended to the end
4. lots of things:
   - identity id https://docs.dash.org/projects/platform/en/latest/docs/protocol-ref/identity.html#identity-id
   - pub key serialization https://docs.dash.org/projects/platform/en/latest/docs/protocol-ref/identity.html#identity-publickeys
   - instantLock is isdlock bytes encoded as RFC Base64 https://docs.dash.org/projects/core/en/stable/docs/reference/p2p-network-instantsend-messages.html#isdlock
